### ISSUE TITLE
deprecated  `FILTER_SANITIZE_STRING`

### ISSUE THREAD

**Issue by gregor-j** [the-kbA-team/markdown-table#3]
Oh, one last issue I forgot to mention: `FILTER_SANITIZE_STRING` is deprecated now (used in both `Column` and `Table`. I think we want to use `FILTER_SANITIZE_SPECIAL_CHARS` now. I'm happy to make a case for this if you'd like.

_Originally posted by @alexekorn in https://github.com/the-kbA-team/markdown-table/issues/2#issuecomment-1130114116_

**Comment by gregor-j** [comment]
_Deprecated as of PHP 8.1.0, use [htmlspecialchars()](https://www.php.net/manual/en/function.htmlspecialchars.php) instead._

https://www.php.net/manual/en/filter.filters.sanitize.php

**Comment by gregor-j** [comment]
@alexekorn `FILTER_SANITIZE_SPECIAL_CHARS` seems like a good replacement. I will commit the changes, as I'm already on it.

**Comment by gregor-j** [comment]
thanks @alexekorn for reporting that

**Comment by alexekorn** [comment]
@gregor-j Thanks for the quick fix!
